#!/bin/sh
# Generate HTML from given SGML docbook document
./xmlstarlet tr --omit-decl --docbook http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl sgml/docbook1.sgml | \
    ./xmlstarlet fo --html --indent-spaces 2
